name: Production Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # --------------------------------------------------------------------------------
  # Faz o Checkout dos fontes, gera o os executáveis, gera o instalador e faz deploy
  # para o ambiente de produção.
  # --------------------------------------------------------------------------------
  Build-Deploy-to-Production:
    if: (github.event_name == 'push') &&
        (github.base_ref == 'main' || github.ref_name == 'main')
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        shell: powershell
        run: .\build-main.bat
      
      - name: Deploy to Production
        run: echo "Publicando build em ambiente de produção"